# Default configuration
spring:
  application:
    name: BenedictineHealthApp
  datasource:
    initialization-mode: NEVER
    url: jdbc:mysql://localhost:3306/health_app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
server:
  ssl:
    key-alias: spring-https
    key-store: classpath:enactapi.jks
    key-store-type: JKS
    key-password: password
    key-store-password: password

  port: 7777
