# Default configuration
spring:
  application:
    name: BenedictineHealthApp
  datasource:
    initialization-mode: NEVER
    url: jdbc:mysql://heroku_aebacbd4c8589ef
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: b7041c9c694e96
    password: 98c9f69b
server:
  ssl:
    key-alias: spring-https
    key-store: classpath:enactapi.jks
    key-store-type: JKS
    key-password: password
    key-store-password: password

  port: 7777
