CREATE TABLE IF NOT EXISTS `topic`
(
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(64) NOT NULL,
    `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `idtopic_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `topic_name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;
