CREATE TABLE IF NOT EXISTS `food_log_entry`
(
    `id` INT NOT NULL AUTO_INCREMENT,
    `meal_type` VARCHAR(16) NOT NULL,
    `meal_time` DATETIME NOT NULL,
    `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB
