ALTER TABLE `food`
    ADD `base_id`                              INT            NOT NULL,
    ADD `alcohol_in_grams`                     DECIMAL(10, 4) NOT NULL,
    ADD `polyunsaturated_fatty_acids_in_grams` DECIMAL(10, 4) NOT NULL,
    ADD `monounsaturated_fatty_acids_in_grams` DECIMAL(10, 4) NOT NULL,
    ADD `insoluble_fiber_in_grams`             DECIMAL(10, 4) NOT NULL,
    ADD `soluble_fiber_in_grams`               DECIMAL(10, 4) NOT NULL,
    ADD `added_sugars_in_grams`                DECIMAL(10, 4) NOT NULL,
    ADD `caffeine_in_milligrams`               DECIMAL(10, 4) NOT NULL,
    ADD `iron_in_milligrams`                   DECIMAL(10, 4) NOT NULL,
    ADD `potassium_in_milligrams`              DECIMAL(10, 4) NOT NULL,
    ADD `phosphorus_in_milligrams`             DECIMAL(10, 4) NOT NULL,
    ADD `thiamin_in_milligrams`                DECIMAL(10, 4) NOT NULL,
    ADD `riboflavin_in_milligrams`             DECIMAL(10, 4) NOT NULL,
    ADD `niacin_in_milligrams`                 DECIMAL(10, 4) NOT NULL,
    ADD `pantothenic_acid_in_milligrams`       DECIMAL(10, 4) NOT NULL,
    ADD `vitamin_b6_in_milligrams`             DECIMAL(10, 4) NOT NULL,
    ADD `vitamin_b12_in_micrograms`            DECIMAL(10, 4) NOT NULL,
    ADD `vitamin_c_in_milligrams`              DECIMAL(10, 4) NOT NULL,
    ADD `folate_in_micrograms`                 DECIMAL(10, 4) NOT NULL,
    ADD `vitamin_a_in_international_units`     DECIMAL(10, 4) NOT NULL,
    ADD `beta_carotene_in_micrograms`          DECIMAL(10, 4) NOT NULL,
    ADD `lycopene_in_micrograms`               DECIMAL(10, 4) NOT NULL,
    ADD `vitamin_d_in_micrograms`              DECIMAL(10, 4) NOT NULL,
    ADD `vitamin_e_in_international_units`     DECIMAL(10, 4) NOT NULL,
    RENAME COLUMN `sodium_in_grams` TO `sodium_in_milligrams`;
